<a href="https://colab.research.google.com/github/rshaabaan/retail-sales-analytics/blob/main/src/features_engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
df_orders = cleaned_data['Orders']
df_orders['profit_margin'] = (df_orders['profit'] / df_orders['sales']) * 100
df_orders['profit_margin']

0       16.00
1       30.00
2       47.00
3      -40.00
4       11.25
        ...
9989    16.25
9990    17.00
9991     7.50
9992    45.00
9993    30.00
Name: profit_margin, Length: 9993, dtype: float64

In [ ]:
df_orders['shipping_duration'] = (df_orders['ship_date'] - df_orders['order_date']).dt.days

df_orders['shipping_duration']

0       3
1       3
2       4
3       7
4       7
       ..
9989    2
9990    5
9991    5
9992    5
9993    5
Name: shipping_duration, Length: 9993, dtype: int64

In [ ]:
avg_shipping_by_mode = df_orders.groupby('ship_mode')['shipping_duration'].mean()
print(avg_shipping_by_mode)

In [ ]:
df_orders['is_discounted'] = df_orders['discount'] > 0
df_orders['is_discounted']

In [ ]:
df_orders['revenue_per_unit'] = df_orders['sales'] / df_orders['quantity']
df_orders['revenue_per_unit']

In [ ]:
df_returns = cleaned_data['Returns']
returned_order_ids = df_returns['order_id'].unique()
df_orders['is_returned'] = df_orders['order_id'].isin(returned_order_ids)
df_orders['is_returned']